### ISSUE TITLE
Weather trigger won't work properly

### ISSUE THREAD

**Issue by Krosta8** [pie-flavor/Consensus#1]
Hello,
I have version 1.2.0 installed and wanted to use the weather trigger.
It is doing something, but only send message to console "10"

Could you please repair this?
Here is my config: https://hastebin.com/ebesuzecek.swift
Using SpongeForge 1.12.2 Build 2825
Consensus 1.2.0

And question about API 5.2.0, should it working on this version too? (not tried yet, just asked)

**Comment by pie-flavor** [comment]
I notice you don't have your min-players configured; were there more than ten players on your server? And no, it doesn't. Only an API 5 release would work on API 5.

**Comment by pie-flavor** [comment]
Although, shit, I did leave a debug message in.

**Comment by Krosta8** [comment]
Sorry for this. I didn't see the min-player :D 
Could you please do the weather trigger for API 5 release too? I would like to use it on my Pixelmon server, which is on version 1.10.2 API 5.2.0
